#! /usr/bin/env php

<?php

require_once __DIR__.'/vendor/autoload.php';

ini_set('xdebug.var_display_max_depth', 12);
ini_set('xdebug.var_display_max_children', 256);
ini_set('xdebug.var_display_max_data', 1024);
ini_set('xdebug.cli_color',2);

/**
 * ---------------------------------------------------
 * Sandbox
 * ---------------------------------------------------
 *
 * Sandbox environment to quickly experiment with features of the Vine package.
 * This is used for development purposes and showcases.
 */

$records = [
        ['id' => 1,'name' => 'foobar-1', 'parent_id' => 0],
        ['id' => 2,'name' => 'foobar-2', 'parent_id' => 1],
        ['id' => 3,'name' => 'foobas-3', 'parent_id' => 1],
        ['id' => 4,'name' => 'foobar-4', 'parent_id' => 0],
        ['id' => 5,'name' => 'foobar-5', 'parent_id' => 3],
];

echo "\n";
